### ISSUE TITLE
Import problems

### ISSUE THREAD

**Issue by kfitzpatrick** [philippschulte/fastly-postman#1]
When I selected all three files in the import file browser, it received two identical messages:

> Failed to import data: Could not import: TypeError: Cannot read property 'id' of null

It did however import a bunch of stuff. Not sure how big of a deal this is.

![postman_and_philippschulte_fastlyapicollection__postman_collection_for_the_fastly_api](https://user-images.githubusercontent.com/24348/28221531-8880b1bc-6878-11e7-9b0c-5e4a19273d01.png)

**Comment by philippschulte** [comment]
Don't worry about the error message. I don't know why Postman is throwing this error but I have tested the setup and everything is working like a charm!
